#-----------------------------------------------------------------------------
# GNUmakefile used to check-out special Miriad doc files.
#
# Original: 2007/11/28, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2007/11/28 03:19:56 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
