#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad include files.
#
# Original: 2007/03/23, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2007/03/23 03:48:07 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
