#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad source files.
#
# Original: 2009/01/16, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2009/01/16 06:33:36 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
