#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad catalogue files.
#
# Original: 2009/02/09, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2009/02/09 01:30:16 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
