#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad include files.
#
# Original: 2006/09/19, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2006/10/04 06:17:43 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
