#-----------------------------------------------------------------------------
# GNUmakefile used to checkout and/or install architecture-specific Miriad
# scripts.
#
# Original: 2006/10/04, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2006/10/04 06:29:23 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
