#-----------------------------------------------------------------------------
# GNUmakefile used to checkout and/or install architecture-specific Miriad
# scripts.
#
# Original: 2011/03/23, Mark Calabretta, ATNF
# $Id: GNUmakefile,v 1.1 2011/03/23 01:21:52 cal103 Exp $
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
