.TH atmerge 1
.SH NAME
atmerge - Merge ancillary information with an AT-observed uv file.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
uv analysis
.SH DESCRIPTION
ATMERGE merges certain ancillary information of an AT observation
into the corresponding Miriad uv file.
.SH PARAMETERS
.TP
\fIvis\fP
The names of the input uv data sets. No default.
.TP
\fItsys\fP
Either one of two names, being the text files containing the
system temperatures for the various antennas. If one value is
given, then the Tsys for the X and Y channels are assumed to be the
same. If two values are given, the first is assumed to be X, then
second is Y. The default is no tsys file.
.TP
\fIxyphase\fP
The name of a text file containing the XY phases. The default is
no xyphase file.
.TP
\fIchi\fP
The name of a text file containing the RPFITS parallactic angle
data. This results in the variable ``errchi'', which gives
the difference between the Miriad value and the RPFITS value.
Default is no chi file.
.TP
\fIxyamp\fP
The name of the text file containing the XY-amplitude data.
This results in the variable ``xyamp'' being written. Default is
no xy-amplitude file.
.TP
\fIout\fP
The name of the output uv data set. No default.
