.TH copyhd 1
.SH NAME
copyhd - Copy items from one data-set to another.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
utility
.SH DESCRIPTION
COPYHD is a Miriad task which copies items from one Miriad data-set
to another. There is no interpretation of the items at all.
.SH PARAMETERS
.TP
\fIin\fP
Name of the input data set. No default.
.TP
\fIout\fP
Name of the output data set. This must already exist. No default.
.TP
\fIitems\fP
A list of items to be copied across. At least one value must be
given.
