.TH gplist 1
.SH NAME
gplist - List information about calibration tables.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
calibration
.SH DESCRIPTION
GpList is a Miriad task to list information about visibility
calibration tables and to check their consistency.
.SH PARAMETERS
.TP
\fIvis\fP
The input dataset containing the visibility calibration tables.
