.TH gpshift 1
.SH NAME
gpshift - Shift the frequency of bandpass solutions.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
calibration
.SH DESCRIPTION
.SH PARAMETERS
.TP
\fIvis\fP
The name of the input data-set. This will normally be a visibility
data-set. No default.
.TP
\fIoffset\fP
Frequency offset to add, in GHz. Default is 0.
