.TH hanning 1
.SH NAME
hanning - Smooth a cube along the spectral axis
.SH PERSON RESPONSIBLE
bpw
.SH CATEGORIES
map combination
.SH DESCRIPTION
Hanning does a Hann or boxcar smooth on the spectral axis of
a Miriad image cube.  It determines the axis from the header,
or else assumes that it is the z-axis.  Masked pixels are
zeroed before smoothing.
For very large cubes hanning smoothing the 3rd axis can be
too slow, it may be much quicker to use reorder to put the
spectral axis first, then run hanning, and then reorder back.
.sp
.SH PARAMETERS
.TP
\fIin\fP
.nf
 The input image.  No default.
.fi
.sp
.TP
\fIout\fP
.nf
 The output image.  No default.
.fi
.sp
.TP
\fIregion\fP
.nf
 Region of the input image to process.
.fi
.sp
.TP
\fIobject\fP
.nf
 hanning or boxcar.  Default is hanning.
.fi
.sp
.TP
\fIwidth\fP
.nf
 The number of channels over which to smooth.  Must be an odd
 number.  Default is 3.
.fi
.sp
.SH REVISION
1.7, 2016/09/14 03:44:47 UTC
