.TH imblr 1
.SH NAME
imblr - Replace blanked pixels in an image with the specified value
.SH PERSON RESPONSIBLE
nebk
.SH CATEGORIES
image analysis
.SH DESCRIPTION
IMBLR replaces any pixel that is blanked by an unblanked pixel
with value specified by the user.
.sp
.SH PARAMETERS
.TP
\fIin\fP
Input image.  Wild card expansion supported.
.TP
\fIout\fP
Output image
.TP
\fIvalue\fP
Value to replace blanked pixels by. Default is zero.
.sp
.SH REVISION
1.5, 2013/08/30 01:49:21 UTC
