.TH imsub 1
.SH NAME
imsub - Extract subportion of an image
.SH PERSON RESPONSIBLE
mchw
.SH CATEGORIES
map manipulation
.SH DESCRIPTION
IMSUB is a MIRIAD task which extracts a subportion of an image.
.SH PARAMETERS
.TP
\fIin\fP
The input image. No default.
.TP
\fIout\fP
The output image. No default.
.TP
\fIregion\fP
The region of interest. The default is the entire input image.
See the Users Manual for instructions on how to specify this.
.TP
\fIincr\fP
Increment to be used along each axis. Default is 1.
.sp
.SH REVISION
1.6, 2013/08/30 01:49:21 UTC
