.TH mathd 1
.SH NAME
mathd - Perform mathematical operations on items.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
utility
.SH DESCRIPTION
MATHD is a MIRIAD task which performs mathematical operations on
items in a Miriad data-set. The items can be either a single value,
or a ``vector'' of values.
.SH PARAMETERS
.TP
\fIin\fP
Name of the input data-set. No default.
.TP
\fIitem\fP
Name of the output item, in the data set. No default.
.TP
\fIexp\fP
The expression to compute. This is an expression in FORTRAN-like
syntax (like MATHS),
