.TH mirhelp 1
.SH NAME
mirhelp - Give help on a Miriad task
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
user utility
.SH DESCRIPTION
Usage: mirhelp [-w] [-k keyword] task
.sp
mirhelp gives help on a Miriad task.
.sp
Options:
.nf
  -w    Use the netscape browser to display the help.
  -k    Get help about a specific task keyword.
.fi
.sp
