.TH mospsf 1
.SH NAME
mospsf - Determine approximate PSF of a mosaic experiment
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
map combination
.SH DESCRIPTION
MOSPSF is a MIRIAD task that determines the point spread
function for a linear mosaic of dirty images (as produced by
INVERT).
.sp
Strictly speaking, the PSF varies with position and frequency.
However if the pointing grid is fairly complete and the
individual synthesised beam patterns are similar, the PSF is
reasonably independent of position.  It is also usually a good
approximation that it is independent of frequency.
.SH PARAMETERS
.TP
\fIbeam\fP
This gives the name of the input beam-cube (as produced by
INVERT).  No default.
.TP
\fIout\fP
The name of the output point-spread function.  It will be the
same size as the input.
.TP
\fIradec\fP
The RA and DEC (either in the form hh:mm:ss,dd:mm:ss or decimal
hours and degrees) at which to compute the point-spread
function.  The default is the reference RA,DEC of the beam-cube.
.TP
\fIfreq\fP
The frequency (in GHz) at which to compute the point-spread
function.  The default is the reference frequency of the beam-
cube.  The point-spread function is reasonably independent of
frequency for most spectral line observations.
.sp
.SH REVISION
1.7, 2017/07/27 05:46:46 UTC
