.TH mossen 1
.SH NAME
mossen - Determine the rms and gain in a mosaiced image.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
map combination
.SH DESCRIPTION
MOSSEN determines the rms and gain of a mosaiced image.  Both
of these parameters are a function of position (and also mildly
frequency dependent).
.sp
.SH PARAMETERS
.TP
\fIin\fP
The input map of interest. No default.
.TP
\fIregion\fP
The standard region of interest parameter, giving the region
where the sensitivity function is to be determined. The default
is the entire input image.
.TP
\fIsen\fP
The output image giving the rms as a function of position.
The default is that this image is not created.
.TP
\fIgain\fP
The output image giving the gain to a unit point source as a
function of position. To avoid noise amplification at the
edge of mosaiced regions, Miriad does not normally totally
correct for the primary beam beyond a certain point. The default
is that no gain image is formed.
.sp
.SH REVISION
1.5, 2018/11/29 23:30:11 UTC
