.TH paraplot 1
.SH NAME
paraplot - Plot parallactic and elevation angle for a source.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
utility
.SH DESCRIPTION
PARAPLOT plots parallactic angle and elevation as a function of
hour angle.
.SH PARAMETERS
.TP
\fIlat\fP
Observatory latitude, in degrees. The default is the AT's latitude.
.TP
\fIelev\fP
Elevation limit, in degrees. Default is 15 degrees.
.TP
\fIdec\fP
Source declination, in degrees. Default is the same declination
as the observatory.
.TP
\fIdevice\fP
PGPLOT device. Default is no plot.
.TP
\fIlog\fP
Log file. Default is no log file.
