.TH planets 1
.SH NAME
planets - Print ephemerides of planets and the Sun.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
utility
.SH DESCRIPTION
PLANETS is a MIRIAD task to report some parameters on solar system
objects. An approximate builtin ephemeris is also available.
.sp
.SH PARAMETERS
.TP
\fIsource\fP
This can be "sun" or the name of a major planet (excluding the Earth).
Some of the moons of Jupiter and Saturn are also recognized, the parent
planet will remain to control the output, but an additional line will
report the diameter of that moon.
No default.
.TP
\fIepoch\fP
The time (UTC) for which information is required, in standard
Miriad time format (yymmmdd.ddd or yymmmdd:hh:mm:ss.s).
For example 11DEC25:18:02:01.2
No default.
.TP
\fItelescop\fP
The name of an observatory used in computing rise and set times.
The default is not to compute these. See telepar for a list of
observatories that Miriad knows about.
