.TH prthis 1
.SH NAME
prthis - List history item of a dataset
.SH PERSON RESPONSIBLE
bpw
.SH CATEGORIES
utility
.SH DESCRIPTION
PRTHIS is a MIRIAD task to list the history item of a miriad
dataset.
.SH PARAMETERS
.TP
\fIin\fP
Standard keyword in. See the help on "in" for more information.
.TP
\fIbcount\fP
The first line to list. Default is 1.
.TP
\fIlog\fP
The name of the output listing file. The default is the terminal
.TP
\fItask\fP
List history only of this list of tasks (max=5). Default is all tasks.
