.TH rpfread 1
.SH NAME
rpfread - Output information about an ATNF RPFITS file
.SH PERSON RESPONSIBLE
tw
.SH CATEGORIES
utilities
.SH DESCRIPTION
RPFREAD summarises basic information about an RPFITS file.  Less
information is reported for ATCA data, which is detected based
on the "INSTRUMENT" card.
.sp
.SH PARAMETERS
.TP
\fIin\fP
Input RPFITS file.  No default.
.TP
\fItformat\fP
Time format, choose "hms" for HH:MM:SS.S or "raw" for decimal.
Default is decimal.
.TP
\fIposout\fP
Optional text file to write out (u,v,w) values (Mopra/PKS only).
These contain the UT time (seconds), RA & DEC position stamps
for OTF mapping.  Default is not to write this file.
.TP
\fItsysout\fP
Optional text file to write out Tsys values (Mopra/PKS only).
These contain the UT time (seconds), systemps, SDO, and GTP
values.  Default is not to write this file.  Cannot be used with
options=brief or options=header.
.TP
\fIoptions\fP
Extra processing options.
'brief'  Output a one-line summary for each scan.
'header' Output only the source/frequency header information.
.sp
.SH REVISION
1.12, 2010/09/21 23:49:07 UTC
