.TH shifty 1
.SH NAME
shifty - Align two images.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
image analysis
.SH DESCRIPTION
SHIFTY is a MIRIAD task that shifts one image by an integral
number of pixels to align it as well as possible with another
image.
.SH PARAMETERS
.TP
\fIin1\fP
The first input image is considered to be the master.
No default.
.TP
\fIin2\fP
The second input image is shifted to align it with the master.
No default.
.TP
\fIout\fP
The output image.  No default.
.sp
.SH REVISION
1.5, 2013/08/30 01:49:21 UTC
