.TH specshift 1
.SH NAME
specshift - shift velocity profiles
.SH PERSON RESPONSIBLE
tw
.SH CATEGORIES
analysis
.SH DESCRIPTION
SPECSHIFT shifts all spectra in a cube according to a 2-D
template (a velocity field).  The velocity of the template is
made the central pixel of the spectrum.  If the template is
blanked or out-of-range the spectrum is unchanged.  Based on
Bart Wakker's HANNING.
.sp
.SH PARAMETERS
.TP
\fIin\fP
.nf
 The input data cube.  No default.
.fi
.sp
.TP
\fItin\fP
.nf
 The template image, should be 2-D with same RA/DEC axes as the
 input cube.
.fi
.sp
.TP
\fIout\fP
.nf
 The output image.  No default.
.fi
.sp
.TP
\fIregion\fP
.nf
 The region of the input cube to modify.  Default is the whole
 cube.
.fi
.sp
.TP
\fIrefpix\fP
.nf
 The velocity pixel which will be assigned to the template
 velocity.  Default is the middle pixel of the v-range.
.fi
.sp
.TP
\fIoptions\fP
.nf
 doblank    Don't wrap profile around; blank if out of range.
            By default the edge channels are assumed to be
            noise so the profile is wrapped when shifting
            beyond edges.
.SH REVISION
1.7, 2012/03/13 02:21:33 UTC
