.TH telepar 1
.SH NAME
telepar - Report telescope characteristics.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
utility
.SH DESCRIPTION
TELEPAR reports the characteristics of various observatories.
Its main use is to check that the characteristics are correct.
.sp
.SH PARAMETERS
.TP
\fItelescop\fP
Name of the observatory.  Several can be given.  If none are
given, TELEPAR simply lists the known observatories.
.sp
.SH REVISION
1.8, 2013/08/30 01:49:21 UTC
