.TH tvinit 1
.SH NAME
tvinit - Initialize a TV device
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
visual display
.SH DESCRIPTION
TVINIT is a MIRIAD/Werong task which initializes a TV device. These
initializations clear the screen, set pan, zoom and colour lookup
table to their defaults.
.SH PARAMETERS
.TP
\fIserver\fP
The TV device. No default. See the Users Manual for information
on how to specify this.
