.TH tvset 1
.SH NAME
tvset - Set up and initialize the TV device.
.SH PERSON RESPONSIBLE
rjs
.SH DESCRIPTION
TVSET either sets the lookup table, or clears the TV device.
.SH PARAMETERS
.TP
\fIserver\fP
Standard keyword server. See the help on "server" for more information.
No default.
.TP
\fItable\fP
This gives the name of the operation to perform, or look-up
table to load. Possible values are:
.nf
  'clear'    Reset the TV device.
  'grey'     Black and white look-up table.
  'colour'   Colour look-up table.
  'rainbow'  Another colour look-up table.
