.TH uvpflag 1
.SH NAME
uvpflag - Flag correlations of certain polarizations when template
.SH PERSON RESPONSIBLE
nebk
.SH CATEGORIES
calibration
.SH DESCRIPTION
UVPFLAG will flag all correlations of specified polarizations
when ALL given template polarizations are flagged.   This can be
useful, for example, if you run TVFLAG, and flag data based upon
the XX correlation.  You then use UVPFLAG and flag all other
correlations of the same baseline and time when the XX correlations
are flagged.
.sp
.SH PARAMETERS
.TP
\fIvis\fP
.nf
  Input visibility file. No default.
.TP
\fIpolt\fP
  Template polarizations.  No default. Can be upto 4 polarizations
  separated by commas from the following list:
          xx, yy, xy, yx, rr, ll, rl, lr, i, q, u, v
.TP
\fIpols\fP
  Slave polarizations to flag when ALL template polarizations
  are bad.  No default. Choose up to 4 from the list given
  for keyword `polt'.
.TP
\fIoptions\fP
  Task enrichment options.  Minimum match is active.
.fi
.sp
.nf
  or      By default, UVPFLAG flags the slaves when ALL
          of the templates are flagged.  This option
          directs it to flag the slaves when ANY one of
          the templates are flagged.
  full    Instructs UVPFLAG to tell you about every record
          it flags.  The default is a summary at the end.
