.TH varlist 1
.SH NAME
varlist - List all variables in dataset
.SH PERSON RESPONSIBLE
lgm
.SH CATEGORIES
utility, plotting
.SH DESCRIPTION
VARLIST lists all variable names or names, types and length
in a data set.
.SH PARAMETERS
.TP
\fIvis\fP
Standard keyword vis. See the help on "vis" for more information.
.TP
\fIlog\fP
Name of output file
.TP
\fIoption\fP
Option for printout (names or all).  Default is "all."
