.TH varmerge 1
.SH NAME
varmerge - Merge in a new visibility variable.
.SH PERSON RESPONSIBLE
rjs
.SH CATEGORIES
uv analysis
.SH DESCRIPTION
.SH PARAMETERS
.TP
\fIvis\fP
The input visibility data set
.TP
\fIout\fP
The output visibility data set, with the new variable added
.TP
\fIvar\fP
The name of the variable to be merged in.
.TP
\fIdata\fP
A text file containing the variable. It is in the form
of a time stamp followed by the variable.
